apiVersion: v1
kind: Service
metadata:
  name: sky-webserver
  namespace: sky
spec:
  selector:
    tier: backend
    layer: webserver
  ports:
    - protocol: TCP
      port: 10088
      targetPort: 80
