apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky-fpm
  namespace: sky
  labels:
    tier: backend
    layer: fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  template:
    metadata:
      labels:
        tier: backend
        layer: fpm
    spec:
      initContainers:
        - name: migrations
          image: 192.168.2.11:5000/sky/cli:v0.0.1
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          envFrom:
            - configMapRef:
                name: sky
            - secretRef:
                name: sky
      containers:
        - name: fpm
          image: 192.168.2.11:5000/sky/fpm_server:v0.0.1
          ports:
            - containerPort: 9000
      
